import { Guild, GuildInvitation } from '../lib/types';

// Mock Guilds Data
export const mockGuilds: Guild[] = [
    {
        id: 'guild-1',
        name: 'Morning Warriors',
        description: 'Rise early, conquer the day. Focused on morning routines and productivity.',
        avatar: '⚔️',
        bannerImage: undefined,
        createdBy: 'user-1',
        createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        members: [
            {
                userId: 'user-1',
                userName: 'You',
                userAvatar: '🎯',
                role: 'owner',
                joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 2400,
                streakDays: 45,
            },
            {
                userId: 'user-2',
                userName: 'Emma Wilson',
                userAvatar: '🎨',
                role: 'admin',
                joinedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 1850,
                streakDays: 38,
            },
            {
                userId: 'user-3',
                userName: 'Alex Chen',
                userAvatar: '💪',
                role: 'member',
                joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 980,
                streakDays: 22,
            },
            {
                userId: 'user-4',
                userName: 'Jordan Smith',
                userAvatar: '🌟',
                role: 'member',
                joinedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 520,
                streakDays: 12,
            },
        ],
        maxMembers: 10,
        isPublic: true,
        totalXP: 5750,
        level: 12,
        season: 'winter-2024',
    },
];

// Mock Public Guilds for Discovery
export const mockPublicGuilds: Guild[] = [
    {
        id: 'guild-2',
        name: 'Fitness Fanatics',
        description: 'Get fit together! Daily workout challenges and healthy habit tracking.',
        avatar: '💪',
        createdBy: 'user-10',
        createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        members: [
            {
                userId: 'user-10',
                userName: 'Coach Mike',
                userAvatar: '🏋️',
                role: 'owner',
                joinedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 4200,
                streakDays: 78,
            },
            {
                userId: 'user-11',
                userName: 'Sarah J',
                userAvatar: '🏃',
                role: 'member',
                joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 2100,
                streakDays: 52,
            },
            {
                userId: 'user-12',
                userName: 'Tom K',
                userAvatar: '🚴',
                role: 'member',
                joinedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 1600,
                streakDays: 40,
            },
        ],
        maxMembers: 15,
        isPublic: true,
        totalXP: 7900,
        level: 15,
        season: 'winter-2024',
    },
    {
        id: 'guild-3',
        name: 'Mindful Creators',
        description: 'Meditation, journaling, and creative pursuits. Build mindfulness together.',
        avatar: '🧘',
        createdBy: 'user-20',
        createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        members: [
            {
                userId: 'user-20',
                userName: 'Zen Master',
                userAvatar: '☮️',
                role: 'owner',
                joinedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 1800,
                streakDays: 42,
            },
            {
                userId: 'user-21',
                userName: 'Luna',
                userAvatar: '🌙',
                role: 'member',
                joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
                contributedXP: 950,
                streakDays: 28,
            },
        ],
        maxMembers: 8,
        isPublic: true,
        totalXP: 2750,
        level: 7,
        season: 'winter-2024',
    },
    {
        id: 'guild-4',
        name: 'Code & Coffee',
        description: 'Developers building better coding habits. Daily commits and learning streaks.',
        avatar: '💻',
        createdBy: 'user-30',
        createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
        members: Array.from({ length: 12 }, (_, i) => ({
            userId: `dev-${i}`,
            userName: `Developer ${i + 1}`,
            userAvatar: i % 2 === 0 ? '👨‍💻' : '👩‍💻',
            role: i === 0 ? 'owner' : i < 3 ? 'admin' : 'member',
            joinedAt: new Date(Date.now() - (120 - i * 5) * 24 * 60 * 60 * 1000).toISOString(),
            contributedXP: 3000 - i * 200,
            streakDays: 90 - i * 5,
        })) as any,
        maxMembers: 15,
        isPublic: true,
        totalXP: 18600,
        level: 22,
        season: 'winter-2024',
    },
];

// Mock Guild Invitations
export const mockGuildInvitations: GuildInvitation[] = [
    {
        id: 'ginv-1',
        guildId: 'guild-2',
        guildName: 'Fitness Fanatics',
        guildAvatar: '💪',
        fromUserId: 'user-10',
        fromUserName: 'Coach Mike',
        toUserId: 'user-1',
        status: 'pending',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
];
